# Generated by Django 3.1.5 on 2021-01-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to=None)),
                ('head', models.TextField()),
                ('title', models.TextField()),
                ('Content', models.TextField()),
                ('btn_text', models.TextField()),
                ('btn_url', models.URLField()),
                ('fact_title', models.TextField()),
                ('fact_desc', models.TextField()),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
                'db_table': 'about1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AboutIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField()),
                ('category', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'AboutIcon',
                'verbose_name_plural': 'AboutIcons',
                'db_table': 'aboutIcon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AboutMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('milestone', models.TextField()),
            ],
            options={
                'verbose_name': 'AboutMilestone',
                'verbose_name_plural': 'AboutMilestones',
                'db_table': 'aboutMilestone',
                'managed': True,
            },
        ),
    ]
