# Generated by Django 3.1.5 on 2021-01-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='about',
            table='about',
        ),
    ]
