# Generated by Django 3.1.5 on 2021-01-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210118_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='btn_url',
            field=models.TextField(),
        ),
    ]
