# Generated by Django 3.1.5 on 2021-01-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210120_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='hide',
            name='name',
            field=models.TextField(default='Link'),
        ),
    ]
