# Generated by Django 3.1.5 on 2021-01-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hide_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigate',
            name='name',
            field=models.TextField(default='Nav'),
        ),
    ]
