# Generated by Django 3.1.5 on 2021-01-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_navigate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouticon',
            name='name',
            field=models.TextField(default='Icon'),
        ),
    ]
