# Generated by Django 3.1.5 on 2021-01-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_abouticon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmilestone',
            name='name',
            field=models.TextField(default='Milestone'),
        ),
    ]
