# Generated by Django 3.1.5 on 2021-01-23 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_aboutmilestone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='vimage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/video/'),
            preserve_default=False,
        ),
    ]
