# Generated by Django 3.1.5 on 2021-01-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_setting_navlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='wbg_name',
            field=models.TextField(default='How I Work'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.TextField(default='Resume'),
        ),
    ]
