# Generated by Django 3.1.5 on 2021-01-24 05:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210124_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workprocess',
            name='btn',
        ),
        migrations.RemoveField(
            model_name='workprocess',
            name='btn_link',
        ),
        migrations.RemoveField(
            model_name='workprocess',
            name='text',
        ),
        migrations.AddField(
            model_name='resume',
            name='btn',
            field=models.TextField(default='MY SERVICES'),
        ),
        migrations.AddField(
            model_name='resume',
            name='btn_link',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='text',
            field=models.TextField(default='Need more info ? Visit my services page :'),
        ),
    ]
