# Generated by Django 3.1.5 on 2021-01-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210124_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillset',
            options={'managed': True, 'ordering': ['count'], 'verbose_name': 'Skillset', 'verbose_name_plural': 'Skillsets'},
        ),
        migrations.AddField(
            model_name='setting',
            name='particles',
            field=models.IntegerField(default=90),
        ),
    ]
