# Generated by Django 3.1.5 on 2021-01-25 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210124_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='aIconBg',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/about/'),
            preserve_default=False,
        ),
    ]
