# Generated by Django 3.1.5 on 2021-01-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210125_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='hide',
            name='menu',
            field=models.BooleanField(default=True),
        ),
    ]
