# Generated by Django 3.1.5 on 2021-01-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_hide_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hide',
            name='company_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hide',
            name='sec1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hide',
            name='sec2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hide',
            name='sec3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hide',
            name='sec4',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hide',
            name='sec5',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hide',
            name='sec6',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hide',
            name='social',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hide',
            name='video',
            field=models.BooleanField(default=True),
        ),
    ]
