# Generated by Django 3.1.5 on 2021-02-06 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210125_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='fact_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/about/fact'),
            preserve_default=False,
        ),
    ]
